version: "3.8"
services:
  db:
    container_name: postgres-task-manager
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    environment:
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    image: postgres:alpine3.18
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  backend:
    container_name: backend-nest-task-manager
    build:
      context: .
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - ${PORT}:4242
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - TYPEORM_HOST=db
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
